<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: evan_chang
 * Date: Fri, 08 Oct 2010 23:07:38 -0600
 */

$conf['title'] = 'Programming Languages @ CU';
$conf['start'] = 'news';
$conf['template'] = 'typo';
$conf['breadcrumbs'] = 0;
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['rss_linkto'] = 'current';
$conf['tpl']['A_Centered_Perspective']['closedwiki'] = '1';
$conf['tpl']['A_Centered_Perspective']['hideactions'] = '1';

// end auto-generated content
